version: '3'

services:
  front-end:
    build: ./front-end
    volumes:
      - ./front-end:/home/node/app
    ports:
      -  "4200:4200"
    depends_on:
      - back-end
  back-end:
    build: ./back-end
    volumes:
      - ./back-end:/home/node/app
    ports:
      - "3000:3000"